AAFC-BICoE/object-store-api

- pom.xml
Removed unnecessary crnk libs + fix the name of the mapstruct artifact
> Support #17650 Fix issues in pom.xml

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/resources/db/changelog/db.changelog-init.xml
- src/main/resources/static/json-schema/getOneMetadataSchema.json
- src/test/java/ca/gc/aafc/objectstore/api/mapper/ObjectStoreMetadataDtoMapperTest.java
> Support #17888 Add acTags to backend

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/main/java/ca/gc/aafc/objectstore/api/file/FolderStructureStrategy.java
- src/main/java/ca/gc/aafc/objectstore/api/minio/MinioFileService.java
- src/test/java/ca/gc/aafc/objectstore/api/TestConfiguration.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FolderStructureStrategyTest.java
Initial folder strcture strategy. The strategy is transparent for the user of MinioFileService since it's an implementation detail.
> Feature #18041 Store objects in folder structure

- src/main/java/ca/gc/aafc/objectstore/api/dto/ManagedAttributeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/resources/db/changelog/db.changelog-init.xml
- src/main/resources/static/json-schema/getOneMetadataSchema.json
- src/test/java/ca/gc/aafc/objectstore/api/crud/ManagedAttributeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
Added fields to liquibase migration, entity, dto and static json schema
> Support #18437 Add created fields to metadata and managed attributes

- src/main/java/ca/gc/aafc/objectstore/api/ObjectStoreConfiguration.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectStoreMetadataFactory.java
- src/main/resources/application.yml
- src/main/resources/db/changelog/db.changelog-init.xml
- src/main/resources/static/json-schema/getOneMetadataSchema.json
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreMetadataJsonApiIT.java
Added missing terms and default value support for xmpRightsOwner
> Feature #18551 Add missing terms acCaption and xmpRightsOwner

- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/MetadataManagedAttributeRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/main/resources/db/changelog/db.changelog-init.xml
Added 2 new types to dcType and changed the default to UNDETERMINED.
Test coverage is still missing and will be part of the refactoring of assignDefaultValues
> Bug #18679 Set default value for dcType

- docs/agent_upload_retrieval.adoc
- docs/index.adoc
https://redmine.biodiversity.agr.gc.ca/issues/18693
Added agent_upload_retrieval.adoc file, adding documentation for uploading and retreiving agent information
> Support #18693 Review and update documentation for 0.1

- src/main/java/ca/gc/aafc/objectstore/api/respository/DcTypeJsonSerDe.java
- src/main/resources/static/json-schema/getOneMetadataSchema.json
- src/main/resources/static/json-schema/getOneObjectSubtypeSchema.json
fixed the DcTypeSerializer, schema and tests
> Bug 18785 Object store API returns DcType value instead of label string,

- src/main/resources/application.yml
Changed application.yml to disable the feature
> Support #18891 Disable JPA open-in-view

- README.md
- local/.env.example
- local/docker-compose.yml.example
Fixed issues .env file and docker-compose file to make sure postgres user is not overlapping with the app user
> Support 19003 More improvements to local setup

- src/test/java/ca/gc/aafc/objectstore/api/rest/DcTypeJsonSerializationIT.java
Make sure RestAssured baseURI and Path are always initialized
> Bug #19149 Intermitent failure of DcTypeJsonSerializationIT

- .travis.yml
- README.md
- local/docker-compose.yml.example
Updated the local docker-compose, travis file and fixed issues in the README
> Feature #19145 Move Object-Store Postgres to 10

- local/docker-compose.yml.example
Renamed PATH_FROM_COMPOSE and removed unused Keycloak variable
> Support #19209 Rename PATH_FROM_COMPOSE in local docker-compose

- docs/file_upload_download.adoc
reflect current code of object-store.api
https://redmine.biodiversity.agr.gc.ca/issues/19277
- Updated file_upload_download.adoc
> In Progress - Support #19277 - Correct file_upload_download.adoc to

- src/test/java/ca/gc/aafc/objectstore/api/rest/BaseJsonApiIntegrationTest.java
Removed call to parseAndValidate..(), replaced assertSchema() with assertRemoteSchema()
> Change OpenAPI3 assertions

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileUploadIT.java
Restricts file upload and downloads to authorized buckets only
> 19460 restrict bucket access by group

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
Allow file uploads to continue if an image thumbnail fails to generate
> 19556_Image_upload_error

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/main/java/ca/gc/aafc/objectstore/api/minio/MinioFileService.java
- src/test/java/ca/gc/aafc/objectstore/api/TestConfiguration.java
Bump minio version with related changes
> 19514 update minio client

- pom.xml
Updated SpringBoot and removed dependencies that are managed by dina-base-api.
> Support #19604 Update dependencies

- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
https://redmine.biodiversity.agr.gc.ca/issues/19587
-Removed default group filter.
> Feedback Support #19587 Remove strict group restriction

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
bump version in pom and fix error in ObjectStoreResourceRepository
> 19645 bump dina version to 30

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
Remove group authentication from file download.
Also removed the related test
> 19691_remove_authenticate_bucket_on_download

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
https://redmine.biodiversity.agr.gc.ca/issues/19664
Added group in metadata entity and dto
> Support 19663 Add group to metadata entity

- pom.xml
- src/test/java/ca/gc/aafc/objectstore/api/DinaAuthenticatedUserConfig.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileUploadIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/BaseJsonApiIntegrationTest.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/DcTypeJsonSerializationIT.java
updated dina-base, removed dependencies provided by dina-base from the pom, fixed issues.
> Support #19770 Update dina-base-api to 0.31

- src/main/java/ca/gc/aafc/objectstore/api/respository/ManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ManagedAttributeService.java
Change repo for managed attribute to extend dina repo and added the needed dina service class
> 19756_manage_attribute_uses_new_dina_layers

- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectSubtypeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectSubTypeService.java
Change subtype repo to use dina repo and dina service layer
> 19747_subtype_uses_dina_layers

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/respository/ManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectSubtypeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ManagedAttributeService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectSubTypeService.java
- src/test/java/ca/gc/aafc/objectstore/api/BaseIntegrationTest.java
- src/test/java/ca/gc/aafc/objectstore/api/auditing/AuditListenerIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/BaseEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ManagedAttributeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectSubtypeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/BaseRepositoryTest.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/BaseJsonApiIntegrationTest.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/DcTypeJsonSerializationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/MetadataManagedAttributeJsonApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreMetadataJsonApiIT.java
> 19838_bump_dina_base_0.32

- src/main/java/ca/gc/aafc/objectstore/api/respository/auditlog/AuditSnapshotRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/AuditService.java
- src/test/java/ca/gc/aafc/objectstore/api/service/AuditServiceIT.java
Abstracts audit snap shot data access from the audit repo into a separate layer.
Introduces the AuditService, currently provides methods for find all and get resource count.
> 19843 auditing service layer

- checkstyle.xml
> 19946_checkstyle_prevent_tab

- pom.xml
Update dependencies and remove unused version properties
> Support #20110 Dependencies update

- src/main/resources/application.yml
Added Spring configuration for graceful shutdown
> Feature #18410 Add shutdown hook and prepare to shutdown

- src/main/resources/db/changelog/migrations/16-MetaData_add_createBy_createdOn.xml
- src/main/resources/db/changelog/migrations/17-MetaManagedAttrib_add_createdBy_createdOn.xml
Update migrations 16 and 17 to migrate exsisting records for created by
> 20129 Migration 14 fails

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/MediaTypeToDcTypeConfiguration.java
- src/main/java/ca/gc/aafc/objectstore/api/ObjectStoreConfiguration.java
Cleaned pom.xml and added some finals where useful.
> Support #20226 Minor fixes

- src/main/java/ca/gc/aafc/objectstore/api/dto/ManagedAttributeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ManagedAttribute.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ManagedAttributeCRUDIT.java
- Update dto and entity for removal of attribute
- Update tests that called for the attribute
> 19952 Remove created date for managed attribute

- pom.xml
- src/test/java/ca/gc/aafc/objectstore/api/service/ManagedAttributePermissionServiceIT.java
-Updated dina-base-api version.
-Changed ManagedAttributePermissionServiceIT to use the new Keycloak annotatin instead of Mockito.
> Feedback 20314

- .travis.yml
- README.md
- pom.xml
- src/test/java/ca/gc/aafc/objectstore/api/AppStartsIT.java
- src/test/java/ca/gc/aafc/objectstore/api/BaseHttpIntegrationTest.java
- src/test/java/ca/gc/aafc/objectstore/api/BaseIntegrationTest.java
- src/test/java/ca/gc/aafc/objectstore/api/auditing/AuditListenerIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/BaseEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileUploadIT.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ManagedAttributePermissionServiceIT.java
- src/test/resources/application-test.yml
-Updated dina-base-api version.
-Added application-test.yml test config file.
-Added required annotations / base classes to test classes for test container support.
> Feedback Support #20323 Add test container support for obejct-store-api

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/main/java/ca/gc/aafc/objectstore/api/file/ThumbnailService.java
-Added pdfbox dependency.
-Added custom handling in ThumbnailGenerator to handle pdf thumbnails..
> Feedback Support #20504 Create PDF thumbnails

- pom.xml
Changed object-store-api tu put the real dev version.
Updated outdated dependecnies
> Support #20585 Update dependencies

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/MetadataManagedAttributeRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectSubtypeResourceRepository.java
Removed @JsonInclude(Include.NON_EMPTY) annotations.
> Feedback 20574

- src/main/java/ca/gc/aafc/objectstore/api/minio/MinioFileService.java
add removeFile to the MinioFileService for future use with hard deletes
> 20815 add MinioFileService delete

- src/main/java/ca/gc/aafc/objectstore/api/entities/MetadataManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/managedattributemap/ManagedAttributeMapRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/managedattributemap/MetadataToManagedAttributeMapRepository.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/managedattributemap/ManagedAttributeMapRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ManagedAttributeAuditingIT.java
Enables auditing of managed attributes for metadata
> 20772 audit managed attributes

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/test/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDtoTest.java
> 20932 bump dina base 0.42

- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
Sets up Ac Derived From to be a One to many relation with a list of Derivatives.
Tests updated to prove its usage
> 20842 add dervative metadata

- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetadataDefaultValueSetterService.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetadataDefaultValueSetterServiceTest.java
Moved default values setting to Service level
> Support #20977 Move DefaultValueSetter to Service level

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ManagedAttributeAuditingIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreMetadataJsonApiIT.java
Exposes the many side of ac derived from -> derivatives relationship on the dto.
Test cases updated to validate.
> 20958 expose meta derivatives

- src/main/java/ca/gc/aafc/objectstore/api/respository/managedattributemap/ManagedAttributeMapRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/MetaManagedAttributeService.java
- Branch off dev
- Add services to Add Service to ManagedAttributeMapRepository
> Support 21066 Add Service to ManagedAttributeMapRepository

- owasp-suppression.xml
- pom.xml
Added suppress rule for Keycloak
> 21097 Fix owasp reported security issue

- Dockerfile
Removed multistage to use the output from maven
> 21105 Remove multistage build from Dockerfile object-store-api

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/MainConfiguration.java
bump dina base and remove bean
> 21250 update dina base 45

- src/main/java/ca/gc/aafc/objectstore/api/FileUploadConfiguration.java
- src/main/java/ca/gc/aafc/objectstore/api/ObjectStoreApiLauncher.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/FileUploadConfigDto.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/FileConfigRepository.java
- src/test/java/ca/gc/aafc/objectstore/api/AppStartsIT.java
Opens end point for file upload config
> 21288 expose maximum file upload info

- pom.xml
> 21297 Fix owaps issue

- src/main/java/ca/gc/aafc/objectstore/api/exceptionmapping/PayloadToLargeExceptionMapper.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FilePayloadIT.java
add exception mapper for file controller
> 21300 return 413 when file to big

- owasp-suppression.xml
- pom.xml
Updated dina-base, SpringBoot and other libraries/plugins
> 21442 Update dependencies

- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
remove un-necessary use of assert result set size
> 21742 test delete parent

- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/22-Change-metadata-assignedValue-to-text.xml
-Added migration to Change metadata assignedValue to text.
> Feedback 22055

- src/main/java/ca/gc/aafc/objectstore/api/exif/ExifParser.java
-Add filter for null value in map
> Support 22064 Make extractExifTag more robust

- src/main/java/ca/gc/aafc/objectstore/api/dto/DerivativeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/DerivativeRepository.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/DerivativeRepositoryCRUDIT.java
Example Post `api/v1/derivative/`
```
{
"data": {
"type": "derivative",
"attributes": {
"dcType": "SoUnD",
"fileIdentifier": "40a9d9ab-2be9-46d9-a7f4-beb8419c8c76"
},
"relationships": {
"acDerivedFrom": {
"data": {
"id": "272a0006-3fc3-4ac9-a164-c777d4944e1d",
"type": "metadata"
}
}
}
}
}
```
> 22189 add derivative repo

- src/main/java/ca/gc/aafc/objectstore/api/dto/DerivativeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/Derivative.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/25-remove_subtype_from_derivative.xml
- src/test/java/ca/gc/aafc/objectstore/api/crud/DerivativeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/DerivativeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectSubTypeJsonApiIT.java
- Removes O subtype from derivative
- Adds derivative type enum and column
- removes thumbnail object subtype record
> 22221 remove subtype from derivative

- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
set derivative type for generated thumbnails to THUMBNAIL_IMAGE
> 22235 set derivative type for generated thumbnails

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectSubtypeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectSubtype.java
- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectSubtypeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectSubTypeService.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/1-Remove_app_managed_on_object_sub_type.xml
- src/main/resources/messages.properties
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectSubTypeJsonApiIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22232
> Remove column ObjectSubtype.addManaged

- src/main/java/ca/gc/aafc/objectstore/api/file/MediaTypeDetectionStrategy.java
- src/test/java/ca/gc/aafc/objectstore/api/file/MediaTypeDetectionStrategyTest.java
Improved so it can use the detected type if the extension is known for the detected type
> 22467 Improve MediaTypeDetectionStrategy

- src/main/java/ca/gc/aafc/objectstore/api/entities/AbstractObjectStoreMetadata.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/3-Make_dcFormat_not_null_at_the_database_level.xml
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectStoreMetadataFactory.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectUploadFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/22482
> 22482 make dc format not null at the database level

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22484
> 22484 FileController should return ObjectUpload dto instead of entity

- src/main/java/ca/gc/aafc/objectstore/api/respository/ObjectStoreResourceRepository.java
- src/test/java/ca/gc/aafc/objectstore/api/service/MetaDataAuthorizationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectUploadFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/22485
> 22485 metadata should not use detected media type

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/5-Add_Orientation_field_to_metadata.xml
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectStoreMetadataFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/22578
> Add orientation field to Metadata

- pom.xml
- src/test/java/ca/gc/aafc/objectstore/api/service/MetaDataAuthorizationIT.java
> Support #22550 Update dependencies

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/entities/AbstractObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/MetadataManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectSubtype.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectUpload.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/MetadataManagedAttributeRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/DerivativeService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/DerivativeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ManagedAttributeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectUploadRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/managedattributemap/ManagedAttributeMapRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/managedattributemap/MetadataToManagedAttributeMapRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ManagedAttributeAuditingIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreMetadataJsonApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/service/MetaDataAuthorizationIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22627
> 22627 update to dina base 0.54

- src/test/resources/application-test.yml
> 22807 update minio test image

- src/main/resources/db/changelog/migrations/6-Add_key_to_managed_attribute.xml
changed context to schema-change
> Support #22827 liquibase migration 6 is using wrong context

- src/main/java/ca/gc/aafc/objectstore/api/validation/ObjectStoreManagedAttributeValidator.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreManagedAttributeCRUDIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22873
> 22873 object store managed attribute validator fails on null description

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeService.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreManagedAttributeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeJsonApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributePermissionServiceIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22940
> 22940 update to dina base 0.56

- pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/22956
> 22956 update tika pdfbox minio

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/service/DerivativeService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectSubTypeService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectUploadService.java
bump dina base and adjust services
> 22973 bump dina base 57

- src/test/resources/application-test.yml
> Feedback 23007

- owasp-suppression.xml
https://redmine.biodiversity.agr.gc.ca/issues/22962
> 22962 owasp dependency check failure on dev

- src/test/java/ca/gc/aafc/objectstore/api/minio/MinioTestContainer.java
https://redmine.biodiversity.agr.gc.ca/issues/23092
> 23092 investigate and fix target port 9000 is not exposed

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeAuthorizationService.java
> 23158 dina base 58

- pom.xml
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreManagedAttributeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23271
> 23271 update to dina base 0.59

- pom.xml
> 23293 dina base 60

- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreManagedAttributeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectSubTypeOpenApiIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22913
> 22913 update open api specs to match resources

- .gitignore
- pom.xml
- src/main/resources/db/changelog/db.changelog-init.xml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/1-Remove_app_managed_on_object_sub_type.xml
- src/main/resources/db/changelog/migrations/2-Add_Dc_Format_To_Derivative.xml
- src/main/resources/db/changelog/migrations/3-Make_dcFormat_not_null_at_the_database_level.xml
- src/main/resources/db/changelog/migrations/4-Remove-legacy-soft-delete.xml
- src/main/resources/db/changelog/migrations/5-Add_Orientation_field_to_metadata.xml
- src/main/resources/db/changelog/migrations/6-Add_key_to_managed_attribute.xml
- src/main/resources/db/changelog/migrations/7-re_implement_managed_attributes.xml
https://redmine.biodiversity.agr.gc.ca/issues/23408
> 23408 take liquibase xsd from dina base

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectSubtypeService.java
- src/test/java/ca/gc/aafc/objectstore/api/BaseIntegrationTest.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectSubtypeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectSubtypeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeRepositoryCRUDIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23420
> 23420 field ac subtype should be the same case for entity metadata and object subtype

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectSubtypeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectSubtype.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/8-Add_group_to_ObjectSubtype.xml
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectSubtypeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/DcTypeJsonSerializationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectSubtypeFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/23458
> 23458 object subtype is using group authorization service on dto without group

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/MainConfiguration.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeAuthorizationService.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
- bump dina base
- Adjust auth service for get name
- Adjust Obj Metadata dto to return correct values for group and created date
> 24383 bump dina base 65

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/file/MediaTypeDetectionStrategy.java
> 24403_update_tika_2.1

- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreResourceRepository.java
https://redmine.biodiversity.agr.gc.ca/issues/24492
> remove findOne and findAll ObjectStoreResourceRepository

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectUploadService.java
Updated dina-base and removed dao usage in ObjectUploadService
> 24630 Update to dina-base 0.66

- pom.xml
> 24690_bump_dina_base_67

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectSubtypeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectSubtype.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeResourceRepository.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/9-Remove_group_from_ObjectSubType.xml
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectSubtypeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/DcTypeJsonSerializationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectSubtypeFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/24945
> 24945 remove group from object sub type and make it admin only

- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectUploadService.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectUploadServiceIT.java
adjusted to always parse with seconds
> 25343_date_time_digitized_no_seconds

- src/main/resources/application.yml
added the correct default value for dcRights
> 25218 Fix rights and licence default values

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
https://redmine.biodiversity.agr.gc.ca/issues/25455
> 25455 make object store metadata dto extend attribute meta info provider

- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeService.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreManagedAttributeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeRestIT.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributePermissionServiceIT.java
https://redmine.biodiversity.agr.gc.ca/issues/25456
> 25456 allow object store meta data service to delete unused managed attribute

- src/main/resources/validation-messages.properties
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
https://redmine.biodiversity.agr.gc.ca/issues/25536
> 25536 improve duplicate file warning message

- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/main/java/ca/gc/aafc/objectstore/api/validation/ObjectStoreManagedAttributeValueValidator.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
https://redmine.biodiversity.agr.gc.ca/issues/25527
> 25527 add validation to object store managed attribute keys

- pom.xml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/10-Update_jsonb_path_exists_varchar_function.xml
- src/main/resources/log4j2.yaml
https://redmine.biodiversity.agr.gc.ca/issues/25826
> 25826 update to dina base 0.74

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreManagedAttributeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeService.java
- src/main/java/ca/gc/aafc/objectstore/api/validation/ObjectStoreManagedAttributeValidator.java
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/10-Align_managed_attribute_with_collection-api.xml
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreManagedAttributeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreManagedAttributeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeAuditingIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeRestIT.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributePermissionServiceIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/MultilingualDescriptionFactory.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectStoreManagedAttributeFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/25824
> 25824 align managed attribute with collection api

- pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/25971
> 25971 update dina base 0.75

- src/main/java/ca/gc/aafc/objectstore/api/repository/SupportedLicenseRepository.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/SupportedLicenseRepositoryIT.java
https://redmine.biodiversity.agr.gc.ca/issues/25823
> 25823 improve error handling on unknown fields part 2

- src/main/java/ca/gc/aafc/objectstore/api/file/ThumbnailGenerator.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
https://redmine.biodiversity.agr.gc.ca/issues/26007
> remove legacy thumbnail code

- src/test/java/ca/gc/aafc/objectstore/api/minio/MinioTestContainer.java
- src/test/java/ca/gc/aafc/objectstore/api/minio/MinioTestContainerInitializer.java
https://redmine.biodiversity.agr.gc.ca/issues/26080
> 26080 dynamic port minio test container

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributeAuthorizationService.java
Updated dina-base and affected classes
> 26475 Update to dina-base 0.80

- src/main/java/ca/gc/aafc/objectstore/api/ManagedAttributeConfiguration.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/util/ManagedAttributeIdMapper.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeRepositoryCRUDIT.java
-Added findOne override for fetching by key.
-Added resourceRegistry config.
-Added StringMapper to allow non-uuid strings.
> Feedback 26492

- pom.xml
Updated dina-base and SpringBoot + related dependencies
> 26532 Update to dina-base 0.81

- pom.xml
Updated dina-base, SpringBoot and log4j
> 26890 Update to dina-base 0.84

- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/DerivativeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreManagedAttributeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectSubtypeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/OpenAPIConstants.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
renamed managedAttributes and added OpenAPIConstants to simply tests
> 26924 Rename managedAttributeValues

- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/security/ObjectStoreManagedAttributeAuthorizationService.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributePermissionServiceIT.java
Used hasMinimumRole to allow admin
> 26934 Issue with ObjectStoreManagedAttributeAuthorizationService

- pom.xml
- src/main/resources/db/changelog/db.changelog-init.xml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/1-Remove_app_managed_on_object_sub_type.xml
- src/main/resources/db/changelog/migrations/10-Update_jsonb_path_exists_varchar_function.xml
- src/main/resources/db/changelog/migrations/11-Align_managed_attribute_with_collection-api.xml
- src/main/resources/db/changelog/migrations/12-Add_support_for_type_Link.xml
- src/main/resources/db/changelog/migrations/13-Update_managed_attribute_type_postgres_enum.xml
- src/main/resources/db/changelog/migrations/2-Add_Dc_Format_To_Derivative.xml
- src/main/resources/db/changelog/migrations/3-Make_dcFormat_not_null_at_the_database_level.xml
- src/main/resources/db/changelog/migrations/4-Remove-legacy-soft-delete.xml
- src/main/resources/db/changelog/migrations/5-Add_Orientation_field_to_metadata.xml
- src/main/resources/db/changelog/migrations/6-Add_key_to_managed_attribute.xml
- src/main/resources/db/changelog/migrations/7-re_implement_managed_attributes.xml
- src/main/resources/db/changelog/migrations/8-Add_group_to_ObjectSubtype.xml
- src/main/resources/db/changelog/migrations/9-Remove_group_from_ObjectSubType.xml
updated Liquibase to 4.9.0 and updated migration files
> 26997 Update Liquibase

- pom.xml
Updated imageio and thumbnailator
> 27001 Update dependencies

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/validation/ObjectStoreManagedAttributeValidator.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreManagedAttributeCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/MultilingualDescriptionFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/27158
> Support #27158 - Update to dina base 0.86

- pom.xml
- src/test/resources/application-test.yml
Updated Java client and image for testing
> 28312 Update Minio

- pom.xml
- src/test/java/ca/gc/aafc/objectstore/api/openapi/DerivativeOpenApiIT.java
Updated dependencies and 1 OpenAPI test
> 28321 Update dina-base 0.91

- .github/workflows/ci.yml
- Dockerfile
- README.md
- pom.xml
Updated pom, JaCoCo, CI and Dockerfile
> 28674 Update to Java 17

- src/main/resources/SupportedLicenses.yml
Fixed licence spelling for open-canada licence id
> 28650 Fix licence spelling

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/repository/DerivativeRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectSubtypeResourceRepository.java
Updated dina-base and related code
> 28823 Update to dina-base 0.94

- src/main/java/ca/gc/aafc/objectstore/api/dto/DerivativeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreMetadataDto.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectSubtypeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectUploadDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/AbstractObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/Derivative.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreManagedAttribute.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreMetadata.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectSubtype.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectUpload.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/package-info.java
Added package-info for TypeDef
> 29168 Code cleanup

- src/main/resources/application.yml
Change copyright statement as expressed on https://www.canada.ca/en/canadian-heritage/services/crown-copyright-request.html and https://www.canada.ca/fr/patrimoine-canadien/services/demandes-droit-auteur-couronne.html
> Change value of dcRights statement

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreManagedAttributeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreManagedAttribute.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreManagedAttributeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeAuditingIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeRestIT.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectStoreManagedAttributePermissionServiceIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectStoreManagedAttributeFactory.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/fixtures/ObjectStoreManagedAttributeFixture.java
Updated dina-base and related code.
> 29490 Update dependencies

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectStoreManagedAttributeDto.java
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreManagedAttribute.java
- src/test/java/ca/gc/aafc/objectstore/api/crud/ObjectStoreMetadataEntityCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreManagedAttributeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreManagedAttributeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeAuditingIT.java
- src/test/java/ca/gc/aafc/objectstore/api/rest/ObjectStoreManagedAttributeRestIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/factories/ObjectStoreManagedAttributeFactory.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/fixtures/ObjectStoreManagedAttributeFixture.java
Updated dina-base and fixed related issues.
Breaking change: managed attribute managedAttributeType renamed to vocabularyElementType
> 29668 Update to dina-base 0.100

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
Changed workbook conversion to return a map of sheets instead of a single sheet.
> 29418 Parse multiple sheets of Workbook

- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/security/MetadataAuthorizationService.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/DerivativeOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/openapi/ObjectStoreMetadataOpenApiIT.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/DerivativeRepositoryCRUDIT.java
- src/test/java/ca/gc/aafc/objectstore/api/security/DerivativeRepoAuthorizationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/security/ManagedAttributeAuthorizationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/security/MetadataAuthorizationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/fixtures/DerivativeTestFixture.java
Created MetadataAuthorizationService and cleaned up tests to move all authorization related tests to the security package
> 29756 Add custom authorization to service to metadata

- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/db/changelog/migrations/14-Add_migration_hint_table.xml
- src/main/resources/db/changelog/migrations/data/1-Reset_ObjectUpload_sha1hex.xml
Added hints table + entry for sha1 calculation fix
> 30306 Add migration hint table

- src/main/java/ca/gc/aafc/objectstore/api/service/DerivativeService.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectStoreMetaDataService.java
- src/test/java/ca/gc/aafc/objectstore/api/repository/ObjectStoreMetadataRepositoryCRUDIT.java
Fix thumbnail condition + added new test for it
> 31141 External Resources should not be generating thumbnails

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/entities/ObjectStoreManagedAttribute.java
Updated dina-base, tika, pdfbox
> 31177 Update to dina-base 0.106

- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectUploadResourceRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/security/FileUploadAuthorizationService.java
- src/main/java/ca/gc/aafc/objectstore/api/security/ObjectUploadAuthorizationService.java
- src/test/java/ca/gc/aafc/objectstore/api/security/ObjectUploadAuthorizationIT.java
- src/test/java/ca/gc/aafc/objectstore/api/testsupport/fixtures/ObjectUploadTestFixture.java
Added specialized authorization service for ObjectUpload
> 31328 Allow admin to update file_upload

- src/main/java/ca/gc/aafc/objectstore/api/service/DerivativeService.java
Added a message publish to postPublishEvent to notify the related metadata
> 31837 derivative relationship to metadata should produce message

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
Make sure we can find the file in Minio and compare the size
> 32096 Add additional checks after Minio upload

- docs/file_upload_download.adoc
- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/main/java/ca/gc/aafc/objectstore/api/file/FileObjectInfo.java
- src/main/java/ca/gc/aafc/objectstore/api/security/FileControllerAuthorizationService.java
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
Added new endpoint with documentation and test.
> 32103 Add file storage info endpoint

- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/main/resources/validation-messages.properties
- src/main/resources/validation-messages_fr.properties
- src/test/java/ca/gc/aafc/objectstore/api/file/FileControllerIT.java
Added check on uploaded file size and exception if empty
> 32128 Prevent 0 bytes file

- pom.xml
> Updated dina-base

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectExportDto.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectExportRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectExportService.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectExportServiceIT.java
- Added name field to ObjectExportDto
- Added name arg to ObjectExportService.export
- In ObjectExportRepository, pass ObjectExportDto.name to ObjectExportService.export
- Send filename to ObjectExportNotification
> 33232 Allow ObjectExport to set an export name

- pom.xml
> 33366 Update dina-base to 0.121

- pom.xml
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectOrphanRemovalService.java
Updated dina-base and use the proper method in baseDAO
> 33902 Update dina-base to 0.125

- docs/export_objects.adoc
- src/main/java/ca/gc/aafc/objectstore/api/dto/ObjectExportDto.java
- src/main/java/ca/gc/aafc/objectstore/api/file/FileController.java
- src/main/java/ca/gc/aafc/objectstore/api/file/ObjectExportGenerator.java
- src/main/java/ca/gc/aafc/objectstore/api/repository/ObjectExportRepository.java
- src/main/java/ca/gc/aafc/objectstore/api/service/ObjectExportService.java
- src/main/java/ca/gc/aafc/objectstore/api/util/ObjectFilenameUtils.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectExportServiceIT.java
Added support for filename aliases on object export
> 35745 Allow to provide filename for object export

- docs/export_objects.adoc
- src/main/java/ca/gc/aafc/objectstore/api/config/ExportFunction.java
- src/main/java/ca/gc/aafc/objectstore/api/file/ObjectExportGenerator.java
- src/test/java/ca/gc/aafc/objectstore/api/service/ObjectExportServiceIT.java
resize function nows required factor named param
> 36903 Change ExportFunction to use named params
